# Prettier Configuration File .prettierrc.yaml
# https://prettier.io/docs/en/options.html
# https://prettier.io/docs/en/configuration.html
# Set these global VS Code settings:
# "editor.formatOnSave": true
# "editor.defaultFormatter": "esbenp.prettier-vscode"
# "editor.formatOnSaveTimeout": 2500
# "editor.detectIndentation": false
# "editor.insertSpaces": false
# "editor.tabSize": 4

arrowParens: avoid
bracketSpacing: true
endOfLine: auto
#filepath: <file path>
htmlWhitespaceSensitivity: css
insertPragma: false
jsxBracketSameLine: false
jsxSingleQuote: false
#parser: yaml
printWidth: 120
proseWrap: preserve
quoteProps: as-needed
requirePragma: false
semi: true
singleQuote: true
tabWidth: 2
trailingComma: "none"
useTabs: true
vueIndentScriptAndStyle: false
